// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5t23aDub3CQaIxPxw6GcZwh_4sg9LtBM',
    appId: '1:558309559124:web:2a1cffd287a70f45b996c1',
    messagingSenderId: '558309559124',
    projectId: 'simple-chat-a4a26',
    authDomain: 'simple-chat-a4a26.firebaseapp.com',
    storageBucket: 'simple-chat-a4a26.appspot.com',
    measurementId: 'G-PH4M40EM22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpCs-P2oy3kL61rGcV1gc1nRuGjOLgsg',
    appId: '1:558309559124:android:b62552dccb24fb4eb996c1',
    messagingSenderId: '558309559124',
    projectId: 'simple-chat-a4a26',
    storageBucket: 'simple-chat-a4a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvqXJr4TFtGpabKIiUdmpKjUBg3hzRYAA',
    appId: '1:558309559124:ios:fe33b49428cd2c99b996c1',
    messagingSenderId: '558309559124',
    projectId: 'simple-chat-a4a26',
    storageBucket: 'simple-chat-a4a26.appspot.com',
    iosClientId: '558309559124-6m1hvul428o9vnmst22hk1mub04rj2kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvqXJr4TFtGpabKIiUdmpKjUBg3hzRYAA',
    appId: '1:558309559124:ios:fe33b49428cd2c99b996c1',
    messagingSenderId: '558309559124',
    projectId: 'simple-chat-a4a26',
    storageBucket: 'simple-chat-a4a26.appspot.com',
    iosClientId: '558309559124-6m1hvul428o9vnmst22hk1mub04rj2kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
